### ISSUE TITLE
Consolidating sections on error messaging and troubleshooting

### ISSUE THREAD

**Issue by karaleighh** [LibraryCarpentry/lc-python-intro#100]
Please delete the text below before submitting your contribution. 

---

A quick note that when going through this lesson, I found it a bit jarring to have a section on determining where errors pop up under the "Variable Scope" episode. Would it make more sense to include this within the explanation of various errors that can occur in "Built-in Functions and Help"?  It seems disconnected from the larger flow.

**Comment by chennesy** [comment]
Closing since a major update to the lesson will soon be merged, deprecating most standing issues. Thanks for your contribution!
