### ISSUE TITLE
Possible major updates (LC-CAC)

### ISSUE THREAD

**Issue by chennesy** [LibraryCarpentry/lc-python-intro#108]
Hi @konrad @dheles @elliewix @lwrubel @c-martinez @richyvk, 

LC-CAC (@LibraryCarpentry/curriculum-advisors) recently discussed revamping this Python lesson and making some significant changes. We discussed moving to Jupyter, for example, and replacing the gapminder data with a more library-specific dataset, like the DOAJ data from the OpenRefine lesson. The Carpentries recently reached out to all maintainers and given the response, this lesson officially doesn't have any current active maintainers (cc @tobyhodges). But before moving forward, I wanted to double check with everyone listed in the repo's readme to see if you wanted to continue to work on this lesson. 

If you *do* want to keep working on this, that would be great! We should chat more about possibilities to get the lesson moving towards beta again. Also: no problem if you don't want to work on this any longer. I'm happy to take this one over with some new maintainers and get it on a road towards beta.

thanks, 
Cody

**Comment by elliewix** [comment]
Hi Cody,

As much as I'd love to try and get back on this, I don't think I have the time needed for it. But happy to advise as needed.

**Comment by konrad** [comment]
Thanks @chennesy. Unfortunately, I have the same situation as @elliewix and won't have the time to work on this further. Thanks for taking over.

**Comment by lwrubel** [comment]
Similarly, I can't commit to working on the lesson revamp now. Glad to see this lesson get attention, and thank you for moving this forward, @chennesy!

**Comment by c-martinez** [comment]
Hi @chennesy , I'm in a similar situation. I will check with some of my colleagues to see if they would be able to help out.

**Comment by dheles** [comment]
Hello everyone. I really should have gracefully bowed out of my Carpentries commitments years ago when I took my "new" job. I thought I would still have capacity and context for continuing this work, but that proved not to be the case. @chennesy thanks for taking this baton. I wish all of you the best & look forward to seeing you again somewhere else in LibraryLand.

**Comment by ErinBecker** [comment]
Hi @chennesy - Sorry for the abysmally late response on this. I've added you as a Maintainer for this lesson. Thank you for taking it on!
