### ISSUE TITLE
Format Challenges and Solutions in Lists in Episode 11

### ISSUE THREAD

**Issue by anrastog** [LibraryCarpentry/lc-python-intro#11]
In the "Lists" chapter of Python Intro for Libraries, NONE of the Challenges have Solutions (https://librarycarpentry.github.io/lc-python-intro/11-lists/)

- "Fill in the Blanks"
- "How Large is a Slice?"
- "From Strings to Lists and Back"
- "Working With the End"
- "Stepping Through a List"
- "Slice Bounds"
- "Sort and Sorted"
- "Copying (or Not)"

The solutions for these challenges need to be added.

**Comment by remerjohnson** [comment]
Currently tackling this one. I'm about half way through. Will probably need eyes on how I've worded the solutions :smile:
