### ISSUE TITLE
Format Challenges and Solutions in For Loops in Episode 12

### ISSUE THREAD

**Issue by anrastog** [LibraryCarpentry/lc-python-intro#12]
In the "For Loops" chapter of Python Intro for Libraries, NONE of the Challenges have Solutions (https://librarycarpentry.github.io/lc-python-intro/12-for-loops/)

- Classifying Errors
- Tracing Execution
- Reversing a String
- Practice Accumulating
- Cumulative Sum
- Identifying Variable Name Errors
- Identifying Item Errors

The solutions for these challenges need to be added.

**Comment by ClaraTurp** [comment]
I am suggesting a solution in this issue: https://github.com/LibraryCarpentry/lc-python-intro/issues/77

**Comment by datadopetayo** [comment]
I agree. Having the solutions available would be helpful for novices to understand what the mistakes are and how to fix them.
