### ISSUE TITLE
FYI, Pandas 2.2.2 has bug that affects data visualization episode

### ISSUE THREAD

**Issue by jlchang** [LibraryCarpentry/lc-python-intro#138]
### What is the problem?

FYI, Pandas 2.2.2 seems to have a plotting bug for the plots in [plotting with pandas ](https://broadinstitute.github.io/2024-09-27-python-intro-lesson/data-visualisation.html#plotting-with-pandas), running `albany['circulation'].plot()` renders:
<img width="585" alt="Screenshot 2024-10-04 at 5 12 09 AM" src="https://github.com/user-attachments/assets/0ed0f0b1-c6ef-4cfb-aabe-d1b683ff1320">
instead of:
<img width="597" alt="Screenshot 2024-10-04 at 5 14 11 AM" src="https://github.com/user-attachments/assets/aa28c8ab-47bb-4499-850a-c789064f3dc1">
Pandas `2.0.3` generates the expected plot (Pandas `2.2.3` is also problematic). I [filed an issue](https://github.com/pandas-dev/pandas/issues/59960) in the Pandas repo, the bug is confirmed and a workaround was provided. 

The pandas team is aware so I expect this to be a transient issue but, in the interim, instructors should either avoid pandas 2.2.2/3 or prepend `.plot()` with `.sort_index()`.

### Location of problem (optional)

episodes/data-visualisation.md

**Comment by chennesy** [comment]
Thanks for the heads up @jlchang! I submitted a PR #139 to address this by adding an explanatory instructor note to the data viz episode. Since the pandas team have this on their radar to fix, I don't think we should change the lesson content beyond that.

**Comment by jlchang** [comment]
According to the pandas team, the [change is a feature, not a bug](https://github.com/pandas-dev/pandas/issues/59960#issuecomment-2395060458). So the lesson should probably be updated to insert  .sort-index() before .plot() (which should work for all Python versions) or one could pre-sort the underlying data (less desirable as it leaves a plot of unsorted data as a future point of confusion).

**Comment by chennesy** [comment]
Thanks @jlchang - I'll update the lesson later this week to incorporate `.sort_index()` as needed.
