### ISSUE TITLE
Format Challenges and Solutions in Conditionals in Episode 17

### ISSUE THREAD

**Issue by anrastog** [LibraryCarpentry/lc-python-intro#15]
In the "Conditionals" chapter of Python Intro for Libraries, NONE of the Challenges have Solutions (https://librarycarpentry.github.io/lc-python-intro/17-conditionals/)

- Tracing Execution
- Trimming Values
- Processing Small Files
- Initializing

The solutions for these challenges need to be added.

**Comment by laderast** [comment]
I've added a pull request that added solutions
