### ISSUE TITLE
Format Challenges and Solutions in Data Types and Type Conversion in Episode 3

### ISSUE THREAD

**Issue by kjallen** [LibraryCarpentry/lc-python-intro#21]
In the "Data Types and Type Conversion" chapter of Python Intro for Libraries, not all of the Challenges have Solutions (https://librarycarpentry.github.io/lc-python-intro/03-types-conversion/)

* "Fractions"

* "Automatic Type Conversion"

* "Choose a Type"

* "Division Types"

* "Strings to Numbers"

* "Arithmetic with Different Types"

The solutions for these challenges need to be added.

**Comment by dheles** [comment]
Looks to me like all of the challenges have solutions now. Thanks to those who contributed!
