### ISSUE TITLE
Handout?

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-python-intro#25]
This is a migrated issue.

This lesson might benefit from making a handout of reference materials.  

To do this, add detail of commands/terminology under the keypoints headers for each lesson. This effectively then builds a handout at - for example http://librarycarpentry.github.io/lc-data-intro/reference/ - which can be printed out in advance of the session (librarians love handouts!)

Make sure you make a note of this in your Instructor Notes.

**Comment by dheles** [comment]
Looks like this exists now (if I understand correctly):
https://librarycarpentry.org/lc-python-intro/reference.html

**Comment by konrad** [comment]
I would suggest that we revisit this once the content of the lesson is fixed. The handout could then be adapted to comprise the new content of the lessons.
