### ISSUE TITLE
Replace spyder with jupyter notebook in lesson material

### ISSUE THREAD

**Issue by katrintirok** [LibraryCarpentry/lc-python-intro#27]
Design notes talk about using Jupyter Notebooks, but lesson has an intro to Spyder at the moment.

To stay in synch with other carpentry lessons, use jupyter notebook:

1. add some basic info on jupyter notebook to setup.md and delete info on spyder
2. exchange spyder related info in other lesson with necessary info on jupyter notebook (check design notes and other carpentry lessons - Data Carpentry Ecology, Software Carpentry)

**Comment by cmacdonell** [comment]
Hi @katrintirok, would you be interested in making this change? Just curious.

**Comment by katrinleinweber** [comment]
I'm planning to teach this episode in a week. Practicing it now, so I can't promise that I'll have to time to implement this. If I do, I'll  to notify you all with a PR right away. Please do the same if you find the time to start working on this.

I suggest that whoever starts makes the first PR, works their way from first to last occurrence of `Spyder` while the next person starts at `spyder[-1]` ;-)

**Comment by remerjohnson** [comment]
Just wanted to add that you could also use [Jupyter Lab](http://jupyterlab.readthedocs.io/en/stable/user/interface.html), which imo would give you a more seamless transition from Spyder, since it would retain IDE-like functionality (and file browser, etc.), while giving you the notebook goodness. Although it's still in beta, I feel like it's fairly mature at this point.

**Comment by remerjohnson** [comment]
Fully agreed, @katrinleinweber Thanks!

**Comment by elliewix** [comment]
Notes and items from the maintainer meeting:

* we want to do a larger review of what interfaces we want for the lesson, this needs a larger discussion with the maintainers.
* the whole lesson needs to be reviewed and smoothed out for the references around interfaces

These will likely need to be two separate issues.  Higher priority item but not immediate.

**Comment by katrinleinweber** [comment]
Thank you @chennesy for this and your other recent updates! 🙇
