### ISSUE TITLE
Manifest of Python lesson resources

### ISSUE THREAD

**Issue by lwrubel** [LibraryCarpentry/lc-python-intro#45]
There are a number of resources related to the Python lesson, in addition to this repo and lesson site. The maintainers group is gathering this list as part of our work in developing the Python lesson. 

- [Python for Librarians (library-python repo)](https://github.com/LibraryCarpentry/library-python)
- [Python for Librarians (lesson)](https://librarycarpentry.org/library-python/)
- [Fork of lc-python-intro, lesson page](https://lwrubel.github.io/lc-python-intro/) (Used in Library of Congress workshop)

**Comment by dheles** [comment]
As Belinda points out in issue #3 , there are still issues in the old repo: https://github.com/data-lessons/library-python-intro-DEPRECATED/issues. IDK how many of them are still relevant, but we should probably make an assessment of that.
