### ISSUE TITLE
Format Challenges and Solutions in Variable and Assignments in Episode 2

### ISSUE THREAD

**Issue by anrastog** [LibraryCarpentry/lc-python-intro#6]
In the "Variable and Assignments" chapter of Python Intro for Libraries, not all of the Challenges have Solutions (https://librarycarpentry.github.io/lc-python-intro/02-variables/)

- "Predicting Values"

- "Slicing"

The solutions for these challenges need to be added.

**Comment by remerjohnson** [comment]
I'm going to work on this
