### ISSUE TITLE
Updating Lessons 1-3

### ISSUE THREAD

**Issue by ejones1521** [LibraryCarpentry/lc-python-intro#78]
I would suggest a few changes to lessons 1-3 in Python.

First, I think there needs to be alternate lesson 1's.  One for spyder and one for jupyter.  All the python sessions I have attended have used jupyter.

Second I would  add some of the command line math into lesson 2, that is currently in lesson 1.

Many librarians are going to be complete newbies and it will be important for them to understand data types before they really start using variables. I would take the top section on variable types and using the type function in lesson 3 and insert it into lesson 2 before "variables can be used in calculations."

Third in lesson 2 I would I would move up the case sensitive and meaningful variable names higher up near the beginning of lesson 2.

Finally I would remove index and slicing from lesson two and put them at the end of lesson 3.

---

**Comment by chennesy** [comment]
Closing since a major update to the lesson will soon be merged, deprecating most standing issues. Thanks for your contribution!
