### ISSUE TITLE
Do not use wall clock times in the schedule

### ISSUE THREAD

**Issue by baileythegreen** [LibraryCarpentry/lc-python-intro#82]
Hi, We're using these materials in a workshop next week, and the schedule page has caused a bit of confusion because it says things like it starts at 9.00 and ends at 14.55. I would suggest changing the times in the schedule to just reflect episode lengths, and total time elapsed, as it makes the webpage more general.

Example here:
https://datacarpentry.org/python-ecology-lesson/

**Comment by konrad** [comment]
Many thanks for the suggestion, @baileythegreen.

**Comment by chennesy** [comment]
Closing since a major update to the lesson will soon be merged, deprecating most standing issues. Thanks for your contribution!
