### ISSUE TITLE
Python Intro for Libraries: For Loops - Coding Error under Practice Accumulating 

### ISSUE THREAD

**Issue by RickardCarter** [LibraryCarpentry/lc-python-intro#90]
**In line 290, under _Practice Accumulating_, I believe there is a coding error in the second example, shown here:**

List of word lengths: ["red", "green", "blue"] => [3, 5, 4]
lengths = ____
for word in ["red", "green", "blue"]:
    lengths.____( ____ )
print(lengths)

**The second last line contains a typo--a period instead of an equals sign:**

Instead of:           lengths.____( ____ )
I propose this:     lengths = ____( ____ )

**This correction ensures the code fetches the desired result:**

**Program**

lengths = 0
for word in ["red", "green", "blue"]:
    lengths = len(word)
    print(lengths)

**Result When Run**

3
5
4

**Reference URL**

RE: https://librarycarpentry.org/lc-python-intro/12-for-loops/index.html

**Comment by konrad** [comment]
Thanks @RickardCarter for you suggestion. I think the version in its current form is correct and is intended be filled out in this way:

```
lengths = []
for word in ["red", "green", "blue"]:
    lengths.append(len(word))
print(lengths)
```
