### ISSUE TITLE
Lesson Contribution: Feedback

### ISSUE THREAD

**Issue by Talishask** [LibraryCarpentry/lc-python-intro#91]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

I already went through the total course and made some notes about things which are not totally clear for me. Maybe this helps also to improve the course a little bit. So here are my remarks, questions, ideas and suggestions:

In section "Libraries"
- In the exercise "Exploring the os Library" if the library is imported you can type help(os), but you cannot reach the top of the information. How can this be done?
- it is not clear for me why in the exercise "Locating the Right Module" in the Solution "datetime.date(year, month, day).isoformat()" is used, because it works also without "isoformat()"

In section "For Loops"
- in "The Accumulator pattern turns many values into one." it is maybe an idea to show also the "+=" operator, because it is used in the later exercise "Cumulative Sum"
- for the exercises "Tracing Execution", "Practice Accumulating", "Identifying Variable Name Errors" the Solution is missing

In section "Writing Functions"

- the solution for exercise "Encapsulation" does not work for me. If I use min(data) I get the minimum, but it is a string.
- in exercise "Find the First" the last question is not answered in the Solution
- in exercise "Encapsulate of If/Print Block" some parts of the Solution is missing and in IMHO the solution given for the last part is not taking into account, that there also can be "small" eggs (between 55 and 50 grams).
- I cannot understand the exercise "Encapsulating Data Analysis"

In section "Programming Style"

- After the first example ("Use assertions to check for internal errors.") it is stated "…The source code for the expression that failed will be displayed as part of the error message. …". But this is not true if I use the function with volume = 0. Only the message "AssertionError" is displayed.
- In the example for "Use docstrings to provide online help" it seems that there is a mistake in the last line of the function "average". In the example it is "return sum(values) / average(values)" and I think it should be "return sum(values) / len(values)".
- For the first exercise "What Will Be Shown?" the solution is not fully clear for me. IMHO the first string in the function '''Determine overall maximum edit distance.''' will show up in online help but not the second line '''Avoid checking sequence against itself.''' because it is not at the beginning of the function. I tested the source code and the second line did not show up in online help.
- Exercise "Clean Up This Code": It is not clear for me how to run this program; and for the solution it seems for me that the variable s should be replaced with input_string.

**Comment by konrad** [comment]
Many thanks, @Talishask (and the unknown other member making the suggestions). We are intending a major change of lesson and will see what is left of these suggestion after that but this a great collection of improvement!

**Comment by chennesy** [comment]
Closing since a major update to the lesson will soon be merged, deprecating most standing issues. Thanks for your contribution!
