### ISSUE TITLE
Need more elaboration for Encapsulation Data Analysis section on #10 Writing Functions

### ISSUE THREAD

**Issue by joshuatj** [LibraryCarpentry/lc-python-intro#96]
Encapsulating Data Analysis exercise on Lesson 10 could use some extra elaboration as to what it's trying to achieve. This is the first instance where pandas is in use in this course. For example, it might be worthwhile to explain what df.ix and japan.ix do. Also it might be good to explain what pandas.read_csv do. Took us a while to understand why would a formula to calculate average GDP would only take into account two years. What's unsaid is that the data in the csv only include those two years (1982 and 1987)

The requirement to assume the code has been executed presents a leap in learning difficulty. More scaffolding could be helpful. 

(Thank you for this course. We've been doing one lesson per week and it's far less intimidating and more relevant than other resources we've encounted. Thank you. )

Lesson: https://librarycarpentry.org/lc-python-intro/14-writing-functions/index.html

**Comment by chennesy** [comment]
Closing since a major update to the lesson will soon be merged, deprecating most standing issues. Thanks for your contribution!
