### ISSUE TITLE
Conditionals are used before they are introduced in lesson 13.

### ISSUE THREAD

**Issue by mimkes** [LibraryCarpentry/lc-python-intro#97]
"If statements" are used for the first time in lesson 9 (For Loops)  in "Identifying Variable Name Errors" and also multiple time in lesson 10 "Writing Functions". So lesson 13 "Conditionals" where "if statements" are officially introduced comes too late.

**Comment by chennesy** [comment]
Closing since a major update to the lesson will soon be merged, deprecating most standing issues. Thanks for your contribution!
